"""pi-ai: Unified LLM API for Python."""

from pi.ai.providers.base import Provider as ProviderProtocol
from pi.ai.providers.base import ProviderRegistry, provider
from pi.ai.providers.dummy import DummyProvider
from pi.ai.providers.openai import OpenAIProvider
from pi.ai.stream import complete, stream
from pi.ai.types import (
    Api,
    AssistantContent,
    AssistantMessage,
    CacheRetention,
    Content,
    Context,
    Cost,
    ImageContent,
    KnownApi,
    KnownProvider,
    Message,
    Model,
    ModelCost,
    Provider,
    SimpleStreamOptions,
    StopReason,
    StreamEvent,
    StreamEventDone,
    StreamEventError,
    StreamEventStart,
    StreamEventTextDelta,
    StreamEventTextEnd,
    StreamEventTextStart,
    StreamEventThinkingDelta,
    StreamEventThinkingEnd,
    StreamEventThinkingStart,
    StreamEventToolCallDelta,
    StreamEventToolCallEnd,
    StreamEventToolCallStart,
    StreamOptions,
    TextContent,
    ThinkingBudgets,
    ThinkingContent,
    ThinkingLevel,
    Tool,
    ToolCall,
    ToolParameter,
    ToolResultMessage,
    Transport,
    Usage,
    UserContent,
    UserMessage,
)

__all__ = [
    # Types
    "Api",
    "AssistantContent",
    "AssistantMessage",
    "CacheRetention",
    "Content",
    "Context",
    "Cost",
    "ImageContent",
    "KnownApi",
    "KnownProvider",
    "Message",
    "Model",
    "ModelCost",
    "Provider",
    "SimpleStreamOptions",
    "StopReason",
    "StreamEvent",
    "StreamEventDone",
    "StreamEventError",
    "StreamEventStart",
    "StreamEventTextDelta",
    "StreamEventTextEnd",
    "StreamEventTextStart",
    "StreamEventThinkingDelta",
    "StreamEventThinkingEnd",
    "StreamEventThinkingStart",
    "StreamEventToolCallDelta",
    "StreamEventToolCallEnd",
    "StreamEventToolCallStart",
    "StreamOptions",
    "TextContent",
    "ThinkingBudgets",
    "ThinkingContent",
    "ThinkingLevel",
    "Tool",
    "ToolCall",
    "ToolParameter",
    "ToolResultMessage",
    "Transport",
    "Usage",
    "UserContent",
    "UserMessage",
    # Provider
    "DummyProvider",
    "OpenAIProvider",
    "ProviderProtocol",
    "ProviderRegistry",
    "provider",
    # Streaming
    "complete",
    "stream",
]

__version__ = "0.1.0"
